/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
    
    TriangleNumberCalculator calculate = new TriangleNumberCalculator();

    System.out.println(calculate.value(1));
    System.out.println(calculate.value(2));
    System.out.println(calculate.value(4));

    System.out.println(calculate.add(1, 1));
    System.out.println(calculate.add(2, 3));
    System.out.println(calculate.add(3, 4));

    System.out.println(calculate.subtract(1, 1));
    System.out.println(calculate.subtract(2, 3));
    System.out.println(calculate.subtract(3, 4));
    }
}
